services:
  - type: web
    name: gift-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token-here